"use client"
import { Button } from "../components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "../components/ui/accordion";
import Link from "next/link";
import { Boxes, BrainCircuit, Download, Edit, Layers, Share } from "lucide-react";
import Header from './_components/Header'
import Footer from './_components/Footer'

const working = [
  {
    title: 'Discover AI-powered video creation',
    description: 'Unleash your creativity with AI-generated videos. Simply input your ideas, choose a theme, and let our AI transform your concept into a high-quality video in minutes.'
  },
  {
    title: 'Customize your videos',
    description: 'Take control of your creations with our advanced editing tools. Add text, transitions, music, and effects to personalize your videos, ensuring they meet your unique requirements.'
  },
  {
    title: 'Share your creations',
    description: 'Once your video is ready, easily share it on social media or download it for personal use. Inspire others with your creations and showcase your vision to a global audience.'
  },
  {
    title: 'Download your creations',
    description: 'Collaborate and share your video projects with others on our platform. Get feedback, showcase your work, or even offer your services as a video editor to a community of creators.'
  }
];

const faqs = [
  {
    question: 'What is the purpose of this AI video generator and editor?',
    answer: 'Our platform helps you create and edit professional-quality videos quickly and easily using AI technology, eliminating the need for advanced editing skills.'
  },
  {
    question: 'How does the AI video generator work?',
    answer: 'Simply upload your media or provide a script, and our AI will analyze the input to generate a polished video with scenes, transitions, and music that fit your content.'
  },
  {
    question: 'Can I customize the videos generated by AI?',
    answer: 'Yes! After the AI generates your video, you can fully customize it using our intuitive editor to adjust visuals, text, transitions, music, and more.'
  },
  {
    question: 'What formats are supported for uploading media?',
    answer: 'We support various file formats for images, videos, and audio, including MP4, AVI, MOV, JPEG, PNG, and MP3.'
  },
  {
    question: 'Do I need technical skills to use the platform?',
    answer: 'Not at all! Our platform is designed to be user-friendly, making it accessible for beginners while still offering advanced features for professionals.'
  },
  {
    question: 'Is my data secure on the platform?',
    answer: 'Absolutely! We prioritize data security and use encryption to ensure your files and personal information remain safe.'
  },
  {
    question: 'Are there templates available for different video styles?',
    answer: 'Yes! We provide a variety of templates for business, social media, education, and more, so you can create videos that suit your needs perfectly.'
  },
  {
    question: 'Can I export videos in high resolution?',
    answer: 'Absolutely! You can export your videos in resolutions up to 4K, depending on your subscription plan.'
  },
];

export default function Home() {

  return (
    <div className="bg-black flex flex-col items-center justify-center">
      <Header />
      <div className="bg-black min-h-screen text-gray-100 pt-24">

        {/* Hero Section */}
        <div className="mt-14 relative w-full h-[500px] flex items-center justify-center bg-gradient-to-t from-black via-transparent to-black">
          <img src={'./background2.jpg'} alt="background" className="object-cover w-full h-full opacity-60" />
          <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black bg-opacity-70 flex items-center justify-center text-center">
            <div className="max-w-5xl">
              <h3 className="text-3xl sm:text-5xl md:text-6xl bg-clip-text text-transparent bg-gradient-to-b from-neutral-100 to-gray-500 font-extrabold mb-4">
                Unleash Creativity, Frame by Frame
              </h3>
              <p className="text-md sm:text-lg md:text-xl text-gray-400 mb-4">Turn Your Ideas Into Stunning AI-Generated Videos Effortlessly.</p>
              <Link href="/dashboard">
                <Button className="mt-5 bg-black text-gray-200 text-base font-light hover:text-white hover:bg-black rounded-full px-4 sm:px-6 py-6 border border-white shadow-lg">
                  Get Started
                </Button>
              </Link>
            </div>
          </div></div>

        {/* How It Works Section */}
        <section className="flex flex-col items-center my-10 sm:my-10 py-5 sm:py-10 mx-auto max-w-screen-xl px-4 sm:px-8 bg-gradient-to-b from-transparent via-transparent to-gray-900 rounded-xl shadow-2xl transition-all shadow-gray-500">
          <h2 className="text-2xl sm:text-3xl md:text-4xl -mb-8 font-bold text-center bg-clip-text text-transparent bg-gradient-to-b via-white to-gray-400">How it Works?</h2>
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center bg-clip-text text-transparent bg-gradient-to-r from-gray-700 via-white to-gray-700">_______</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-5 mx-auto">
            {working.map((item, index) => (
              <Card key={index} className={`w-full text-center border-0 bg-transparent shadow-md rounded-lg p-6 ${(index == 1 || index == 2) && 'mt-20'}`}>
                <CardHeader className='flex flex-col items-center'>
                  <div className="border border-white rounded-full pl-2 pr-2 pt-2">
                    {index === 0 && <BrainCircuit className="w-10 h-10 text-gray-400 mb-2 rounded-full" />}
                    {index === 1 && <Edit className="w-10 h-10 text-gray-400 mb-2" />}
                    {index === 2 && <Share className="w-10 h-10 text-4xl text-gray-400 mb-2" />}
                    {index === 3 && <Download className="w-10 h-10 text-4xl text-gray-400 mb-2" />}
                  </div>
                  <CardTitle className="text-lg sm:text-xl mt-2 text-gray-200">{item.title}</CardTitle>
                  <CardDescription className="text-sm text-gray-400 mt-2">
                    {item.description}
                  </CardDescription>
                </CardHeader>
              </Card>
            ))}
          </div>
        </section>

        {/* Features */}
        {/* Features Section */}
<section className="flex flex-col items-center my-10 sm:my-20 py-5 sm:py-10 mx-auto max-w-screen-xl px-4 sm:px-8 bg-gradient-to-b from-transparent via-transparent to-gray-900 rounded-xl shadow-2xl transition-all shadow-gray-500">
  <h2 className="text-2xl sm:text-3xl md:text-4xl -mb-8 font-bold text-center bg-clip-text text-transparent bg-gradient-to-b via-white to-gray-400">Features</h2>
  <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center bg-clip-text text-transparent bg-gradient-to-r from-gray-700 via-white to-gray-700 mb-14">_______</h2>
  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 mx-auto">
    <Card className="text-center border-0 bg-transparent shadow-md rounded-lg p-6">
      <CardHeader>
        <BrainCircuit className="w-12 h-12 text-gray-400 mb-4" />
        <CardTitle className="text-lg sm:text-xl text-gray-200">AI-Powered Video Creation</CardTitle>
        <CardDescription className="text-sm text-gray-400 mt-2">
          Leverage AI technology to create stunning videos with ease and efficiency.
        </CardDescription>
      </CardHeader>
    </Card>
    <Card className="text-center border-0 bg-transparent shadow-md rounded-lg p-6">
      <CardHeader>
        <Edit className="w-12 h-12 text-gray-400 mb-4" />
        <CardTitle className="text-lg sm:text-xl text-gray-200">Advanced Editing Tools</CardTitle>
        <CardDescription className="text-sm text-gray-400 mt-2">
          Customize every detail with intuitive editing tools for a perfect finish.
        </CardDescription>
      </CardHeader>
    </Card>
    <Card className="text-center border-0 bg-transparent shadow-md rounded-lg p-6">
      <CardHeader>
        <Share className="w-12 h-12 text-gray-400 mb-4" />
        <CardTitle className="text-lg sm:text-xl text-gray-200">Effortless Sharing</CardTitle>
        <CardDescription className="text-sm text-gray-400 mt-2">
          Share your creations on social platforms or with your community effortlessly.
        </CardDescription>
      </CardHeader>
    </Card>
    <Card className="text-center border-0 bg-transparent shadow-md rounded-lg p-6">
      <CardHeader>
        <Download className="w-12 h-12 text-gray-400 mb-4" />
        <CardTitle className="text-lg sm:text-xl text-gray-200">High-Quality Downloads</CardTitle>
        <CardDescription className="text-sm text-gray-400 mt-2">
          Download your videos in up to 4K resolution for personal or professional use.
        </CardDescription>
      </CardHeader>
    </Card>
    <Card className="text-center border-0 bg-transparent shadow-md rounded-lg p-6">
      <CardHeader>
        <Boxes className="w-12 h-12 text-gray-400 mb-4" />
        <CardTitle className="text-lg sm:text-xl text-gray-200">Collaborative Platform</CardTitle>
        <CardDescription className="text-sm text-gray-400 mt-2">
          Collaborate with other creators and receive feedback on your projects.
        </CardDescription>
      </CardHeader>
    </Card>
    <Card className="text-center border-0 bg-transparent shadow-md rounded-lg p-6">
      <CardHeader>
        <Layers className="w-12 h-12 text-gray-400 mb-4" />
        <CardTitle className="text-lg sm:text-xl text-gray-200">Template Library</CardTitle>
        <CardDescription className="text-sm text-gray-400 mt-2">
          Access a vast library of templates tailored for various industries and styles.
        </CardDescription>
      </CardHeader>
    </Card>
  </div>
</section>


        {/* FAQ Section */}
        <section className="flex flex-col items-center my-10 sm:my-40 py-5 sm:py-10 mx-auto max-w-screen-xl px-4 sm:px-8 bg-gradient-to-b from-transparent via-transparent to-gray-900 rounded-xl shadow-2xl transition-all shadow-gray-500">
          <h2 className="text-2xl sm:text-3xl md:text-4xl -mb-8 font-bold text-center bg-clip-text text-transparent bg-gradient-to-b via-white to-gray-400">Frequently Asked Questions</h2>
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center mb-14 bg-clip-text text-transparent bg-gradient-to-r from-gray-700 via-white to-gray-700">___________</h2>
          <Accordion type="single" collapsible className="w-full sm:w-3/4 flex flex-col gap-2">
            {faqs.map((item, index) => (
              <AccordionItem key={index} value={`item-${index}`} className='border-0'>
                <AccordionTrigger className="text-lg font-normal text-gray-300 hover:no-underline px-16 py-1 bg-gradient-to-r from-gray-800 via-gray-700 to-gray-800 rounded-xl transition duration-300">{item.question}</AccordionTrigger>
                <AccordionContent className="text-gray-400 px-4 py-2">{item.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </section>
        {/* Footer */}
        <Footer />
      </div>
    </div>
  );
}
